### ISSUE TITLE
Not compatible with ember-data 3.28?

### ISSUE THREAD

**Issue by NullVoxPopuli** [empress/empress-blog#130]
I just upgraded to ember-data 3.28 and got this error:

```
Error occurred:

- While rendering:
  -top-level
    application
      index


There was an error running your app in fastboot. More info about the error: 
 Error: 'content' is a reserved property name on instances of classes extending Model. Please choose a different property name for model:content
    at Class.init (/tmp/broccoli-30854463juidrQY1xVr/out-575-broccoli_merge_trees/assets/addon-tree-output/@ember-data/model/-private.js:3514:1)
    at Class.superWrapper (/tmp/broccoli-30854463juidrQY1xVr/out-575-broccoli_merge_trees/assets/@ember/-internals/utils/index.js:442:1)
    at initialize (/tmp/broccoli-30854463juidrQY1xVr/out-575-broccoli_merge_trees/assets/@ember/-internals/runtime/lib/system/core_object.js:149:1)
    at Function.create (/tmp/broccoli-30854463juidrQY1xVr/out-575-broccoli_merge_trees/assets/@ember/-internals/runtime/lib/system/core_object.js:681:1)
    at FactoryManager.create (/tmp/broccoli-30854463juidrQY1xVr/out-575-broccoli_merge_trees/assets/@ember/-internals/container/index.js:531:1)
    at Proxy.create (/tmp/broccoli-30854463juidrQY1xVr/out-575-broccoli_merge_trees/assets/@ember/-internals/container/index.js:245:1)
    at Store.instantiateRecord (/tmp/broccoli-30854463juidrQY1xVr/out-575-broccoli_merge_trees/assets/addon-tree-output/@ember-data/store/-private.js:10861:1)
    at Store._instantiateRecord (/tmp/broccoli-30854463juidrQY1xVr/out-575-broccoli_merge_trees/assets/addon-tree-output/@ember-data/store/-private.js:7903:1)
    at InternalModel.getRecord (/tmp/broccoli-30854463juidrQY1xVr/out-575-broccoli_merge_trees/assets/addon-tree-output/@ember-data/store/-private.js:5782:1)
    at recordForIdentifier (/tmp/broccoli-30854463juidrQY1xVr/out-575-broccoli_merge_trees/assets/addon-tree-output/@ember-data/store/-private.js:2944:1)
    at Class.objectAtContent (/tmp/broccoli-30854463juidrQY1xVr/out-575-broccoli_merge_trees/assets/addon-tree-output/@ember-data/store/-private.js:3047:1)
    at Class.objectAt (/tmp/broccoli-30854463juidrQY1xVr/out-575-broccoli_merge_trees/assets/@ember/-internals/runtime/lib/system/array_proxy.js:188:1)
    at Class.forEach (/tmp/broccoli-30854463juidrQY1xVr/out-575-broccoli_merge_trees/assets/@ember/-internals/runtime/lib/mixins/array.js:661:1)
    at Class.map (/tmp/broccoli-30854463juidrQY1xVr/out-575-broccoli_merge_trees/assets/@ember/-internals/runtime/lib/mixins/array.js:735:1)
    at Class.toArray (/tmp/broccoli-30854463juidrQY1xVr/out-575-broccoli_merge_trees/assets/@ember/-internals/runtime/lib/mixins/array.js:1180:1)
    at new SortBy (/tmp/broccoli-30854463juidrQY1xVr/out-575-broccoli_merge_trees/assets/addon-tree-output/ember-composable-helpers/helpers/sort-by.js:119:1)
```

**Comment by NullVoxPopuli** [comment]
downgrading to ember-data 3.27 resolves. but obvs only short-term solution

**Comment by elwayman02** [comment]
Likely relevant: https://github.com/empress/empress-blog/blob/master/app/models/content.js#L10
