### ISSUE TITLE
Not compatible with Ember Data 5.x

### ISSUE THREAD

**Issue by barryofguilder** [empress/empress-blog#175]
When I upgrade my application to Ember/Ember Data 5, I get the following error when I run:

```
ReferenceError: AbortController is not defined
    at RequestManager.request (webpack://barryofguilder-blog/../rewritten-packages/@ember-data/request.f79f3bc6/index.js?:722:50)
    at Store.request (webpack://barryofguilder-blog/../rewritten-packages/@ember-data/store.415024ce/-private.js?:3872:40)
    at Store.findAll (webpack://barryofguilder-blog/../rewritten-packages/@ember-data/store.415024ce/-private.js?:4999:26)
    at Class.model (webpack://barryofguilder-blog/../rewritten-packages/empress-blog.5ab5e227/routes/application.js?:19:27)
    at Class.deserialize (/var/folders/ym/q109kwld14xgkvfd2bkpwsr80000gn/T/broccoli-31252O6dgVwI90w1P/out-1187-packager_runner_embroider_webpack/assets/@ember/routing/route.js:589:1)
    at UnresolvedRouteInfoByParam.getModel (/var/folders/ym/q109kwld14xgkvfd2bkpwsr80000gn/T/broccoli-31252O6dgVwI90w1P/out-1187-packager_runner_embroider_webpack/assets/router_js.js:772:1)
    at /var/folders/ym/q109kwld14xgkvfd2bkpwsr80000gn/T/broccoli-31252O6dgVwI90w1P/out-1187-packager_runner_embroider_webpack/assets/router_js.js:606:1
    at invokeCallback (/var/folders/ym/q109kwld14xgkvfd2bkpwsr80000gn/T/broccoli-31252O6dgVwI90w1P/out-1187-packager_runner_embroider_webpack/assets/rsvp.js:435:1)
    at publish (/var/folders/ym/q109kwld14xgkvfd2bkpwsr80000gn/T/broccoli-31252O6dgVwI90w1P/out-1187-packager_runner_embroider_webpack/assets/rsvp.js:421:1)
    at invokeWithOnError (/var/folders/ym/q109kwld14xgkvfd2bkpwsr80000gn/T/broccoli-31252O6dgVwI90w1P/out-1187-packager_runner_embroider_webpack/assets/backburner.js.js:282:1)
    at Queue.flush (/var/folders/ym/q109kwld14xgkvfd2bkpwsr80000gn/T/broccoli-31252O6dgVwI90w1P/out-1187-packager_runner_embroider_webpack/assets/backburner.js.js:188:1)
    at DeferredActionQueues.flush (/var/folders/ym/q109kwld14xgkvfd2bkpwsr80000gn/T/broccoli-31252O6dgVwI90w1P/out-1187-packager_runner_embroider_webpack/assets/backburner.js.js:344:1)
    at Backburner._end (/var/folders/ym/q109kwld14xgkvfd2bkpwsr80000gn/T/broccoli-31252O6dgVwI90w1P/out-1187-packager_runner_embroider_webpack/assets/backburner.js.js:773:1)
    at Backburner._boundAutorunEnd (/var/folders/ym/q109kwld14xgkvfd2bkpwsr80000gn/T/broccoli-31252O6dgVwI90w1P/out-1187-packager_runner_embroider_webpack/assets/backburner.js.js:509:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by NullVoxPopuli** [comment]
Need a file like this: https://github.com/universal-ember/ember-primitives/pull/55/files#diff-84b6173e0fc89bf6abeafcc67e3a52c7e5e95699f0d999f34014e872dff63bcbR1

**Comment by MichalBryxi** [comment]
@barryofguilder AFAIK:

- Long term solution is to make the `empress-blog` bootstrap process to create this file for you (or get the past the need for it).
- Fix for your case would be to create a file `my-blog/config/fastboot.js` and put the contents linked above. It fixed that one issue for me.
