### ISSUE TITLE
image in subdir of images causes error

### ISSUE THREAD

**Issue by cah-danmonroe** [empress/empress-blog#27]
If I put an image into a subdirectory of /public/images/ then at startup, I get an error:
When I put the image in /public/images, it's fine.
`
ERROR Summary:

  - broccoliBuilderErrorStack: Error: Input file contains unsupported image format
  - code: [undefined]
  - codeFrame: Input file contains unsupported image format
  - errorMessage: Input file contains unsupported image format
        at ImageResizer
-~- created here: -~-
    at ImageResizer.Plugin (/Users/daniel.monroe/projects/geoquest/blog-danmonroe/node_modules/broccoli-plugin/index.js:7:31)
    at new CachingWriter (/Users/daniel.monroe/projects/geoquest/blog-danmonroe/node_modules/broccoli-caching-writer/index.js:18:10)
    at new ImageResizer (/Users/daniel.monroe/projects/geoquest/blog-danmonroe/node_modules/ember-responsive-image/broccoli-image-writer.js:16:5)
    at Class.resizeImages (/Users/daniel.monroe/projects/geoquest/blog-danmonroe/node_modules/ember-responsive-image/index.js:170:12)
    at addonOptions.forEach (/Users/daniel.monroe/projects/geoquest/blog-danmonroe/node_modules/ember-responsive-image/index.js:192:30)
    at Array.forEach (<anonymous>)
    at Class.postprocessTree (/Users/daniel.monroe/projects/geoquest/blog-danmonroe/node_modules/ember-responsive-image/index.js:191:25)
    at projectOrAddon.addons.reduce (/Users/daniel.monroe/projects/geoquest/blog-danmonroe/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (<anonymous>)
    at addonProcessTree (/Users/daniel.monroe/projects/geoquest/blog-danmonroe/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
-~- (end) -~-
  - errorType: Build Error
`

**Comment by mansona** [comment]
@cah-danmonroe I assume you're using the casper template? I am pretty sure that is the only template that is using responsive images right now so if you are I can transfer this issue over there 👍
